# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddDataWindow(object):
    def setupUi(self, AddDataWindow):
        AddDataWindow.setObjectName("AddDataWindow")
        AddDataWindow.resize(550, 450)
        self.gridLayout = QtWidgets.QGridLayout(AddDataWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.file_btn = QtWidgets.QPushButton(AddDataWindow)
        self.file_btn.setStyleSheet("background-color: #ef8bce; \n"
"color: black;")
        self.file_btn.setObjectName("file_btn")
        self.gridLayout.addWidget(self.file_btn, 0, 0, 1, 1)
        self.textbox = QtWidgets.QTextEdit(AddDataWindow)
        self.textbox.setObjectName("textbox")
        self.gridLayout.addWidget(self.textbox, 1, 0, 1, 1)
        self.submit_btn = QtWidgets.QPushButton(AddDataWindow)
        self.submit_btn.setStyleSheet("background-color: #54d88c; \n"
"color: black;\n"
"")
        self.submit_btn.setObjectName("submit_btn")
        self.gridLayout.addWidget(self.submit_btn, 2, 0, 1, 1)

        self.retranslateUi(AddDataWindow)
        QtCore.QMetaObject.connectSlotsByName(AddDataWindow)

    def retranslateUi(self, AddDataWindow):
        _translate = QtCore.QCoreApplication.translate
        AddDataWindow.setWindowTitle(_translate("AddDataWindow", "Add RAG Data"))
        self.file_btn.setText(_translate("AddDataWindow", "Select File"))
        self.textbox.setPlaceholderText(_translate("AddDataWindow", "Type, paste, and/or click [Select File] to load a documents contents..."))
        self.submit_btn.setText(_translate("AddDataWindow", "Process and Add to Stack"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddDataWindow = QtWidgets.QWidget()
    ui = Ui_AddDataWindow()
    ui.setupUi(AddDataWindow)
    AddDataWindow.show()
    sys.exit(app.exec_())
