# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/workspace_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(718, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBoxWorkspaceSrc = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxWorkspaceSrc.setObjectName("comboBoxWorkspaceSrc")
        self.verticalLayout.addWidget(self.comboBoxWorkspaceSrc)
        self.treeWidgetItemsSrc = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidgetItemsSrc.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeWidgetItemsSrc.setObjectName("treeWidgetItemsSrc")
        self.verticalLayout.addWidget(self.treeWidgetItemsSrc)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBoxWorkspaceDst = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxWorkspaceDst.sizePolicy().hasHeightForWidth())
        self.comboBoxWorkspaceDst.setSizePolicy(sizePolicy)
        self.comboBoxWorkspaceDst.setObjectName("comboBoxWorkspaceDst")
        self.gridLayout_2.addWidget(self.comboBoxWorkspaceDst, 0, 0, 1, 1)
        self.treeWidgetItemsDst = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidgetItemsDst.setObjectName("treeWidgetItemsDst")
        self.gridLayout_2.addWidget(self.treeWidgetItemsDst, 1, 0, 1, 2)
        self.pushButtonWorkspaceNew = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonWorkspaceNew.setObjectName("pushButtonWorkspaceNew")
        self.gridLayout_2.addWidget(self.pushButtonWorkspaceNew, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButtonClose = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.horizontalLayout_4.addWidget(self.pushButtonClose)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionnew_workspace = QtWidgets.QAction(MainWindow)
        self.actionnew_workspace.setObjectName("actionnew_workspace")
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Workspace Manager"))
        self.treeWidgetItemsSrc.headerItem().setText(0, _translate("MainWindow", "type"))
        self.treeWidgetItemsSrc.headerItem().setText(1, _translate("MainWindow", "name"))
        self.treeWidgetItemsDst.headerItem().setText(0, _translate("MainWindow", "type"))
        self.treeWidgetItemsDst.headerItem().setText(1, _translate("MainWindow", "name"))
        self.pushButtonWorkspaceNew.setText(_translate("MainWindow", "new"))
        self.pushButtonClose.setText(_translate("MainWindow", "close"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionnew_workspace.setText(_translate("MainWindow", "new workspace"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
