import os
import json
import requests
from typing import Optional, Dict, Any

class LightRAGClient:
    """
    A Python client for interacting with a remote LightRAG server via HTTP requests,
    with built-in utilities for inspecting LightRAG's local storage.
    """
    def __init__(self, base_url: str = "http://localhost:9621", api_key: Optional[str] = None):
        """
        Initialize the LightRAG HTTP client.
        
        :param base_url: The base URL of the LightRAG API server. Defaults to localhost:9621.
        :param api_key: Optional API key if the remote server is secured.
        """
        self.base_url = base_url.rstrip("/")
        self.session = requests.Session()
        
        self.session.headers.update({
            "Content-Type": "application/json",
            "Accept": "application/json"
        })
        
        if api_key:
            self.session.headers.update({"Authorization": f"Bearer {api_key}"})

    def insert_text(self, text: str) -> Dict[str, Any]:
        """Inserts a text document into the remote LightRAG instance."""
        url = f"{self.base_url}/documents/text"
        try:
            response = self.session.post(url, json={"text": text})
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException as e:
            self._handle_error(e, response)

    def query(self, query_text: str, mode: str = "hybrid", top_k: int = 50, **kwargs) -> Dict[str, Any]:
        """Queries the remote LightRAG instance."""
        url = f"{self.base_url}/query"
        payload = {"query": query_text, "mode": mode, "top_k": top_k}
        payload.update(kwargs)
        
        try:
            response = self.session.post(url, json=payload)
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException as e:
            self._handle_error(e, response)

    def list_documents_api(self) -> Dict[str, Any]:
        """
        Attempts to list documents via the API.
        Note: The official LightRAG server may not support this endpoint by default.
        If it fails, use `inspect_local_storage()` instead.
        """
        url = f"{self.base_url}/documents" # Hypothetical or custom endpoint
        try:
            response = self.session.get(url)
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException as e:
            print("[Warning] API /documents endpoint not found or failed. Ensure your server supports it, or use `inspect_local_storage()`.")
            return {}

    @staticmethod
    def inspect_local_storage(working_dir: str) -> Dict[str, Any]:
        """
        Directly reads LightRAG's storage JSON files to list contents.
        This bypasses the API and reads the exact IDs and names generated by LightRAG.
        
        :param working_dir: Path to the LightRAG storage directory (e.g., './rag_storage')
        :return: A dictionary containing document lists and chunk IDs.
        """
        docs_path = os.path.join(working_dir, "kv_store_full_docs.json")
        chunks_path = os.path.join(working_dir, "kv_store_text_chunks.json")
        
        results = {
            "documents":[],
            "chunk_ids":[],
            "total_documents": 0,
            "total_chunks": 0
        }

        # 1. Parse Full Documents
        if os.path.exists(docs_path):
            with open(docs_path, "r", encoding="utf-8") as f:
                docs_data = json.load(f)
                
            for doc_id, doc_info in docs_data.items():
                results["documents"].append({
                    "id": doc_id,
                    # LightRAG sometimes stores file paths in a metadata dict depending on version
                    "source": doc_info.get("metadata", {}).get("file_path", "Direct Text/Unknown"),
                    "length": len(doc_info.get("content", ""))
                })
            results["total_documents"] = len(docs_data)
        else:
            print(f"[Warning] Docs file not found at: {docs_path}")

        # 2. Parse Text Chunks
        if os.path.exists(chunks_path):
            with open(chunks_path, "r", encoding="utf-8") as f:
                chunks_data = json.load(f)
            
            # The keys of this JSON file are the exact Chunk IDs generated by LightRAG
            results["chunk_ids"] = list(chunks_data.keys())
            results["total_chunks"] = len(chunks_data)
        else:
            print(f"[Warning] Chunks file not found at: {chunks_path}")

        return results

    def _handle_error(self, error: Exception, response: requests.Response = None):
        print(f"[LightRAGClient Error] Request failed: {error}")
        if response is not None and response.text:
            print(f"[LightRAGClient Error] Server returned: {response.status_code} - {response.text}")
        raise error
